services:
  webserver:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../app:/app
    ports:
      - "80:80"

  app:
    build: services/php
    volumes:
      - ../app:/app

  db:
    image: mariadb:latest
    build: services/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}